openapi: 3.0.1
info:
  title: Bad Actor Service
  version: "1.0"
servers:
  - url: http://localhost/BadActor/v1
paths:
  /BadActors:
    post:
      tags:
        - BadActorRequest
      summary: Identifies a source as a "Bad Actor"
      operationId: BadActorRequest
      requestBody:
        description: Bad actor source Id
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        '201':
          description: Bad Actor successfully added 
        '401': 
          description: Unauthorized
        '432': 
          description: Already reported
        '433': 
          description: No such sourceId
        '454':
          description: Unspecified Error
  /Versions:
    servers:
      - url: https://api.example.com/BadActor
        description: Override base path for Versions query
    get:
      tags:
        - RetrieveVersions
      summary: Retrieves all supported versions, vendor parameter is optional.
      operationId: RetrieveVersions
      responses:
        '200':
          description: Versions found
          content:
            application/json:
              schema:
                $ref: 'i3-common.yaml#/components/schemas/VersionsArray'